In [1]:
# 1. Importing Required Libraries
import numpy as np
import pandas as pd


In [2]:
# 2. Creating and Exploring NumPy Arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print("Array 1:", arr1)
print("Array 2:", arr2)

# Sum, product, dot product
print("Sum:", arr1 + arr2)
print("Product:", arr1 * arr2)
print("Dot product:", np.dot(arr1, arr2))

# Array shape and data type
print("Shape of arr1:", arr1.shape)
print("Data type of arr2:", arr2.dtype)


Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]
Sum: [11 22 33 44 55]
Product: [ 10  40  90 160 250]
Dot product: 550
Shape of arr1: (5,)
Data type of arr2: int32


In [3]:
# 3. NumPy Broadcasting Example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

# Adding vector to each row of matrix using broadcasting
broadcasted_sum = matrix + vector

print("Matrix:\n", matrix)
print("Vector:", vector)
print("Broadcasted sum:\n", broadcasted_sum)


Matrix:
 [[1 2 3]
 [4 5 6]]
Vector: [10 20 30]
Broadcasted sum:
 [[11 22 33]
 [14 25 36]]


In [4]:
# 4. Creating Pandas DataFrame with Sample Employee Data (including missing values)
data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", None, "Frank"],
    "Age": [25, 30, None, 45, 28, 35, 42],
    "Department": ["HR", "IT", "IT", "Finance", None, "HR", "IT"],
    "Salary": [50000, 60000, 55000, None, 48000, 52000, 61000],
    "JoiningDate": pd.to_datetime([
        "2018-03-15", "2019-07-22", "2020-01-10", 
        "2017-11-01", "2021-06-19", "2018-09-23", "2019-12-15"
    ])
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)


Original DataFrame:
    EmployeeID     Name   Age Department   Salary JoiningDate
0         101    Alice  25.0         HR  50000.0  2018-03-15
1         102      Bob  30.0         IT  60000.0  2019-07-22
2         103  Charlie   NaN         IT  55000.0  2020-01-10
3         104    David  45.0    Finance      NaN  2017-11-01
4         105      Eva  28.0       None  48000.0  2021-06-19
5         106     None  35.0         HR  52000.0  2018-09-23
6         107    Frank  42.0         IT  61000.0  2019-12-15


In [5]:
# 5. Data Cleaning - Handling Missing Values

# Remove rows where Name or Department is missing (critical info)
df_clean = df.dropna(subset=["Name", "Department"])

# Fill missing Age and Salary with mean values of respective columns
df_clean["Age"] = df_clean["Age"].fillna(df_clean["Age"].mean())
df_clean["Salary"] = df_clean["Salary"].fillna(df_clean["Salary"].mean())

print("\nDataFrame after cleaning missing values:\n", df_clean)



DataFrame after cleaning missing values:
    EmployeeID     Name   Age Department   Salary JoiningDate
0         101    Alice  25.0         HR  50000.0  2018-03-15
1         102      Bob  30.0         IT  60000.0  2019-07-22
2         103  Charlie  35.5         IT  55000.0  2020-01-10
3         104    David  45.0    Finance  56500.0  2017-11-01
6         107    Frank  42.0         IT  61000.0  2019-12-15


C:\Users\nihal\AppData\Local\Temp\ipykernel_2852\579984361.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Age"] = df_clean["Age"].fillna(df_clean["Age"].mean())
C:\Users\nihal\AppData\Local\Temp\ipykernel_2852\579984361.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Salary"] = df_clean["Salary"].fillna(df_clean["Salary"].mean())


In [6]:
# 6. Detecting and Removing Duplicate Rows

# Intentionally add a duplicate row for demonstration
df_clean = pd.concat([df_clean, df_clean.iloc[0:1]], ignore_index=True)
print("\nDataFrame with duplicate row added:\n", df_clean)

# Remove duplicate rows based on all columns
df_clean = df_clean.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", df_clean)



DataFrame with duplicate row added:
    EmployeeID     Name   Age Department   Salary JoiningDate
0         101    Alice  25.0         HR  50000.0  2018-03-15
1         102      Bob  30.0         IT  60000.0  2019-07-22
2         103  Charlie  35.5         IT  55000.0  2020-01-10
3         104    David  45.0    Finance  56500.0  2017-11-01
4         107    Frank  42.0         IT  61000.0  2019-12-15
5         101    Alice  25.0         HR  50000.0  2018-03-15

DataFrame after removing duplicates:
    EmployeeID     Name   Age Department   Salary JoiningDate
0         101    Alice  25.0         HR  50000.0  2018-03-15
1         102      Bob  30.0         IT  60000.0  2019-07-22
2         103  Charlie  35.5         IT  55000.0  2020-01-10
3         104    David  45.0    Finance  56500.0  2017-11-01
4         107    Frank  42.0         IT  61000.0  2019-12-15


In [7]:
# 7. Advanced Indexing and Filtering

# Select employees from the IT department only
it_employees = df_clean[df_clean["Department"] == "IT"]
print("\nEmployees in IT Department:\n", it_employees)

# Select employees with salary greater than 55,000
high_earners = df_clean[df_clean["Salary"] > 55000]
print("\nEmployees with salary > 55000:\n", high_earners)



Employees in IT Department:
    EmployeeID     Name   Age Department   Salary JoiningDate
1         102      Bob  30.0         IT  60000.0  2019-07-22
2         103  Charlie  35.5         IT  55000.0  2020-01-10
4         107    Frank  42.0         IT  61000.0  2019-12-15

Employees with salary > 55000:
    EmployeeID   Name   Age Department   Salary JoiningDate
1         102    Bob  30.0         IT  60000.0  2019-07-22
3         104  David  45.0    Finance  56500.0  2017-11-01
4         107  Frank  42.0         IT  61000.0  2019-12-15


In [8]:
# 8. Sorting and Selecting Specific Columns

# Sort DataFrame by Salary descending
df_sorted = df_clean.sort_values(by="Salary", ascending=False)
print("\nDataFrame sorted by Salary (descending):\n", df_sorted)

# Select only Name and Salary columns
name_salary = df_sorted[["Name", "Salary"]]
print("\nSelected columns (Name and Salary):\n", name_salary)



DataFrame sorted by Salary (descending):
    EmployeeID     Name   Age Department   Salary JoiningDate
4         107    Frank  42.0         IT  61000.0  2019-12-15
1         102      Bob  30.0         IT  60000.0  2019-07-22
3         104    David  45.0    Finance  56500.0  2017-11-01
2         103  Charlie  35.5         IT  55000.0  2020-01-10
0         101    Alice  25.0         HR  50000.0  2018-03-15

Selected columns (Name and Salary):
       Name   Salary
4    Frank  61000.0
1      Bob  60000.0
3    David  56500.0
2  Charlie  55000.0
0    Alice  50000.0


In [9]:
# 9. Grouping Data for Aggregation

# Calculate average salary by Department
avg_salary_dept = df_clean.groupby("Department")["Salary"].mean().reset_index()
print("\nAverage Salary by Department:\n", avg_salary_dept)

# Calculate count and average age per department
dept_stats = df_clean.groupby("Department").agg({
    "EmployeeID": "count",
    "Age": "mean"
}).rename(columns={"EmployeeID": "EmployeeCount", "Age": "AverageAge"})
print("\nDepartment-wise Employee Count and Average Age:\n", dept_stats)



Average Salary by Department:
   Department        Salary
0    Finance  56500.000000
1         HR  50000.000000
2         IT  58666.666667

Department-wise Employee Count and Average Age:
             EmployeeCount  AverageAge
Department                           
Finance                 1   45.000000
HR                      1   25.000000
IT                      3   35.833333


In [10]:
# 10. Adding New Columns with Apply Function

# Define a function to categorize employees based on age
def categorize_age(age):
    if age < 30:
        return "Young"
    elif age < 40:
        return "Mid-age"
    else:
        return "Senior"

# Apply the function to create new column 'AgeGroup'
df_clean["AgeGroup"] = df_clean["Age"].apply(categorize_age)
print("\nDataFrame with new 'AgeGroup' column:\n", df_clean)



DataFrame with new 'AgeGroup' column:
    EmployeeID     Name   Age Department   Salary JoiningDate AgeGroup
0         101    Alice  25.0         HR  50000.0  2018-03-15    Young
1         102      Bob  30.0         IT  60000.0  2019-07-22  Mid-age
2         103  Charlie  35.5         IT  55000.0  2020-01-10  Mid-age
3         104    David  45.0    Finance  56500.0  2017-11-01   Senior
4         107    Frank  42.0         IT  61000.0  2019-12-15   Senior


In [11]:
# 11. Aggregating by New AgeGroup Column

# Calculate average salary by AgeGroup
avg_salary_agegroup = df_clean.groupby("AgeGroup")["Salary"].mean().reset_index()
print("\nAverage Salary by AgeGroup:\n", avg_salary_agegroup)



Average Salary by AgeGroup:
   AgeGroup   Salary
0  Mid-age  57500.0
1   Senior  58750.0
2    Young  50000.0


In [12]:
# 12. Handling Date Columns and Filtering by Date

# Filter employees who joined after 2019-01-01
recent_joins = df_clean[df_clean["JoiningDate"] > "2019-01-01"]
print("\nEmployees who joined after 2019-01-01:\n", recent_joins)



Employees who joined after 2019-01-01:
    EmployeeID     Name   Age Department   Salary JoiningDate AgeGroup
1         102      Bob  30.0         IT  60000.0  2019-07-22  Mid-age
2         103  Charlie  35.5         IT  55000.0  2020-01-10  Mid-age
4         107    Frank  42.0         IT  61000.0  2019-12-15   Senior
